apiVersion: v1
kind: Service
metadata:
  name: maya-app-service
spec:
  selector:
    app: maya-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30080
  type: NodePort